### ISSUE TITLE
SELECT crashes with pyetcd.EtcdKeyNotFound: Key not found

### ISSUE THREAD

**Issue by akuzminsky** [box/etcdb#26]
* Etcd Database Driver version: 1.5.4
* Python version: Python 2.7.5

### Description

SELECT * FROM table leads to a crash.

### What I Did

```
etcd@127.0.0.1> select * from table;
Traceback (most recent call last):
  File "/bin/etcdb", line 11, in <module>
    load_entry_point('etcdb==1.5.4', 'console_scripts', 'etcdb')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/etcdb/cli.py", line 61, in main
    cursor.execute(query)
  File "/usr/lib/python2.7/site-packages/etcdb/cursor.py", line 173, in execute
    db=self._db)
  File "/usr/lib/python2.7/site-packages/etcdb/execute/dml/select.py", line 272, in execute_select
    lock.acquire()
  File "/usr/lib/python2.7/site-packages/etcdb/lock.py", line 213, in acquire
    meta_lock.release()
  File "/usr/lib/python2.7/site-packages/etcdb/lock.py", line 81, in release
    self._etcd_client.delete(key)
  File "/usr/lib/python2.7/site-packages/pyetcd/client.py", line 112, in delete
    return self._request_key(key, method='delete')
  File "/usr/lib/python2.7/site-packages/pyetcd/client.py", line 290, in _request_key
    return self._request_call(uri, method=method, **kwargs)
  File "/usr/lib/python2.7/site-packages/pyetcd/client.py", line 302, in _request_call
    return EtcdResult(getattr(requests, method)(url, **kwargs))
  File "/usr/lib/python2.7/site-packages/pyetcd/__init__.py", line 264, in __init__
    self._raise_for_status(self._payload)
  File "/usr/lib/python2.7/site-packages/pyetcd/__init__.py", line 289, in _raise_for_status
    raise self._exception_codes[error_code](message)
pyetcd.EtcdKeyNotFound: Key not found
```

**Comment by akuzminsky** [comment]
Fixed in 1.5.5
